"""remove akurasi  migration

Revision ID: 388f1540b832
Revises: 439f11ab0420
Create Date: 2025-11-06 16:53:32.962395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '388f1540b832'
down_revision = '439f11ab0420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediksi_kedatangan', schema=None) as batch_op:
        batch_op.drop_column('akurasi_prediksi')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediksi_kedatangan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('akurasi_prediksi', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
