"""Initial migration

Revision ID: 439f11ab0420
Revises: 
Create Date: 2025-11-06 15:28:58.976644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439f11ab0420'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faskes',
    sa.Column('id_faskes', sa.Integer(), nullable=False),
    sa.Column('nama_faskes', sa.String(length=255), nullable=False),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('kapasitas_harian', sa.Integer(), nullable=True),
    sa.Column('tipe_faskes', sa.Enum('RSU', 'RSIA', 'PUSKESMAS', 'KLINIK', name='tipefaskes'), nullable=False),
    sa.PrimaryKeyConstraint('id_faskes')
    )
    op.create_table('peserta',
    sa.Column('id_peserta', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('nik', sa.String(length=16), nullable=True),
    sa.Column('no_bpjs', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('no_hp', sa.String(length=15), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('tanggal_lahir', sa.Date(), nullable=True),
    sa.Column('preferensi_reminder', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_peserta')
    )
    op.create_table('dokter',
    sa.Column('id_dokter', sa.Integer(), nullable=False),
    sa.Column('nama_dokter', sa.String(length=255), nullable=False),
    sa.Column('spesialis', sa.String(length=100), nullable=True),
    sa.Column('id_faskes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_faskes'], ['faskes.id_faskes'], ),
    sa.PrimaryKeyConstraint('id_dokter')
    )
    op.create_table('riwayat_kunjungan',
    sa.Column('id_riwayat', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=False),
    sa.Column('id_faskes', sa.Integer(), nullable=False),
    sa.Column('id_layanan', sa.Integer(), nullable=True),
    sa.Column('tanggal_kunjungan', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_faskes'], ['faskes.id_faskes'], ),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta.id_peserta'], ),
    sa.PrimaryKeyConstraint('id_riwayat')
    )
    op.create_table('jadwal_faskes',
    sa.Column('id_jadwal', sa.Integer(), nullable=False),
    sa.Column('id_dokter', sa.Integer(), nullable=False),
    sa.Column('id_layanan', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jam_mulai', sa.Time(), nullable=True),
    sa.Column('jam_selesai', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['id_dokter'], ['dokter.id_dokter'], ),
    sa.PrimaryKeyConstraint('id_jadwal')
    )
    op.create_table('antrian',
    sa.Column('id_antrian', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=False),
    sa.Column('id_jadwal', sa.Integer(), nullable=False),
    sa.Column('status_antrian', sa.Enum('MENUNGGU', 'DILAYANI', 'BATAL', name='statusantrian'), nullable=False),
    sa.Column('waktu_datang', sa.DateTime(), nullable=True),
    sa.Column('waktu_dilayani', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_jadwal'], ['jadwal_faskes.id_jadwal'], ),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta.id_peserta'], ),
    sa.PrimaryKeyConstraint('id_antrian')
    )
    op.create_table('monitoring_antrian',
    sa.Column('id_monitor', sa.Integer(), nullable=False),
    sa.Column('id_faskes', sa.Integer(), nullable=False),
    sa.Column('id_antrian', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('total_antrian', sa.Integer(), nullable=True),
    sa.Column('rata_waktu_tunggu', sa.Float(), nullable=True),
    sa.Column('akurasi_prediksi', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_antrian'], ['antrian.id_antrian'], ),
    sa.ForeignKeyConstraint(['id_faskes'], ['faskes.id_faskes'], ),
    sa.PrimaryKeyConstraint('id_monitor')
    )
    op.create_table('prediksi_kedatangan',
    sa.Column('id_prediksi', sa.Integer(), nullable=False),
    sa.Column('id_antrian', sa.Integer(), nullable=False),
    sa.Column('waktu_prediksi', sa.DateTime(), nullable=True),
    sa.Column('akurasi_prediksi', sa.Float(), nullable=True),
    sa.Column('update_terakhir', sa.DateTime(), nullable=True),
    sa.Column('sumber_data', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_antrian'], ['antrian.id_antrian'], ),
    sa.PrimaryKeyConstraint('id_prediksi')
    )
    op.create_table('reminder',
    sa.Column('id_reminder', sa.Integer(), nullable=False),
    sa.Column('id_peserta', sa.Integer(), nullable=False),
    sa.Column('id_prediksi', sa.Integer(), nullable=False),
    sa.Column('waktu_kirim', sa.DateTime(), nullable=True),
    sa.Column('jenis_reminder', sa.Enum('SMS', 'EMAIL', 'PUSH', name='jenisreminder'), nullable=False),
    sa.Column('status_kirim', sa.String(length=50), nullable=True),
    sa.Column('pesan', sa.Text(), nullable=True),
    sa.Column('lokasi_trigger', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_peserta'], ['peserta.id_peserta'], ),
    sa.ForeignKeyConstraint(['id_prediksi'], ['prediksi_kedatangan.id_prediksi'], ),
    sa.PrimaryKeyConstraint('id_reminder')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reminder')
    op.drop_table('prediksi_kedatangan')
    op.drop_table('monitoring_antrian')
    op.drop_table('antrian')
    op.drop_table('jadwal_faskes')
    op.drop_table('riwayat_kunjungan')
    op.drop_table('dokter')
    op.drop_table('peserta')
    op.drop_table('faskes')
    # ### end Alembic commands ###
